version: "3.3"
services:
  ms-instructor:
    container_name: ms-instructor
    image: ms-instructor:v1.0.0
    networks: 
      - redinterna

    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ms-instructor.rule=Host(`ms-instructor.product.localhost`)"
      - "traefik.http.routers.ms-instructor.tls=true"
      - "traefik.http.services.ms-instructor.loadbalancer.server.port=5000"
      - "traefik.docker.network=mired"
      - "traefik.http.middlewares.ms-instructor.circuitbreaker.expression=LatencyAtQuantileMS(50.0) > 100"
      - "traefik.http.middlewares.ms-instructor.circuitbreaker.expression=ResponseCodeRatio(500, 600, 0, 600) > 0.25"
      - "traefik.http.middlewares.ms-instructor.circuitbreaker.expression=NetworkErrorRatio() > 0.5"

networks:
  redinterna:
    external: true