version: "3.3"
services:
    traefik:
        image: traefik:v2.11
        container_name: traefik
        restart: unless-stopped
        security_opt:
            - no-new-privileges:true
        command:
            - "--api.insecure=true"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
        ports:
            - "80:80"
            - "8080:8080"
            - "6379:6379"
            - "5432:5432"
            - "443:443"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./config/config.yml:/etc/traefik/config.yml:ro
            - ./config/traefik.yml:/etc/traefik/traefik.yml:ro
            - ./certs:/etc/traefik/certs
        networks:
            - redinterna
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.traefik=true"

networks:
    redinterna:
        external: true
