version: "3.3"
services:
  ms-user:
    container_name: ms-user
    image: ms-user:v1.0.0
    networks: 
      - redinterna
    ports: 
      - 5001:5000
    env_file:
      - ./MS-PowerAPP-Usuario/.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ms-user.rule=Host(`ms-user.powerapp.localhost`)"
      - "traefik.http.routers.ms-user.tls=true"
      - "traefik.http.services.ms-user.loadbalancer.server.port=5000"

  ms-gym_class:
    container_name: ms-gym_class
    image: ms-gym_class:v1.0.0
    networks: 
      - redinterna
    ports: 
      - 5002:5000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ms-gymclass.rule=Host(`ms-gymclass.powerapp.localhost`)"
      - "traefik.http.routers.ms-gymclass.tls=true"
      - "traefik.http.services.ms-gymclass.loadbalancer.server.port=5000"

  ms-instructor:
    container_name: ms-instructor
    image: ms-instructor:v1.0.0
    networks: 
      - redinterna
    ports: 
      - 5003:5000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ms-instructor.rule=Host(`ms-instructor.powerapp.localhost`)"
      - "traefik.http.routers.ms-instructor.tls=true"
      - "traefik.http.services.ms-instructor.loadbalancer.server.port=5000"

  redis:
    image: redis:7-bookworm
    restart: always
    volumes:
      - ./data:/data
      - ./data/redis.conf:/data/redis.conf
    command: redis-server /data/redis.conf --loglevel notice --requirepass ${REDIS_PASSWORD}
    # ports:
    #   - "6379:6379"
    networks:
      - redinterna

networks:
  redinterna:
    external: true