services:
  ms-user:
    container_name: ms-user
    image: ms-user:v1.0.0
    networks: 
      - redinterna
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_URL=${POSTGRES_URL}
      - POSTGRES_DB${POSTGRES_DB}
    ports: 
      - 5001:5000
    env_file:
      - ./MS-PowerAPP-Usuario/.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ms-user.rule=Host(`ms-user.powerapp.localhost`)"
      - "traefik.http.routers.ms-user.tls=true"
      - "traefik.http.services.ms-user.loadbalancer.server.port=5000"
      - "traefik.http.middlewares.ms1.circuitbreaker.expression=LatencyAtQuantileMS(50.0) > 100"
      - "traefik.http.middlewares.ms1.circuitbreaker.expression=ResponseCodeRatio(500, 600, 0, 600) > 0.25"
      - "traefik.http.middlewares.ms1.circuitbreaker.expression=NetworkErrorRatio() > 0.5"

  ms-gym_class:
    container_name: ms-gym_class
    image: ms-gym_class:v1.0.0
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_URL=${POSTGRES_URL}
      - POSTGRES_DB${POSTGRES_DB}
    networks: 
      - redinterna
    ports: 
      - 5002:5000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ms-gymclass.rule=Host(`ms-gymclass.powerapp.localhost`)"
      - "traefik.http.routers.ms-gymclass.tls=true"
      - "traefik.http.services.ms-gymclass.loadbalancer.server.port=5000"
      - "traefik.http.middlewares.ms1.circuitbreaker.expression=LatencyAtQuantileMS(50.0) > 100"
      - "traefik.http.middlewares.ms1.circuitbreaker.expression=ResponseCodeRatio(500, 600, 0, 600) > 0.25"
      - "traefik.http.middlewares.ms1.circuitbreaker.expression=NetworkErrorRatio() > 0.5"

  ms-instructor:
    container_name: ms-instructor
    image: ms-instructor:v1.0.0
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_URL=${POSTGRES_URL}
      - POSTGRES_DB${POSTGRES_DB}
    networks: 
      - redinterna
    ports: 
      - 5003:5000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ms-instructor.rule=Host(`ms-instructor.powerapp.localhost`)"
      - "traefik.http.routers.ms-instructor.tls=true"
      - "traefik.http.services.ms-instructor.loadbalancer.server.port=5000"
      - "traefik.http.middlewares.ms1.circuitbreaker.expression=LatencyAtQuantileMS(50.0) > 100"
      - "traefik.http.middlewares.ms1.circuitbreaker.expression=ResponseCodeRatio(500, 600, 0, 600) > 0.25"
      - "traefik.http.middlewares.ms1.circuitbreaker.expression=NetworkErrorRatio() > 0.5"


networks:
  redinterna:
    external: true