services:
  ms-user:
    image: ms-user:v1.0.0
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_URL=${DB_URL_USER}
      - POSTGRES_DB=${DB_NAME_USER}
      - CONTAINER_USER_SERVICE_URL=${CONTAINER_USER_SERVICE_URL}
      - USER_SERVICE_URL=${USER_SERVICE_URL}
      - CONTAINER_INSTRUCTOR_SERVICE_URL=${CONTAINER_INSTRUCTOR_SERVICE_URL}
      - INSTRUCTOR_SERVICE_URL=${INSTRUCTOR_SERVICE_URL}
      - CONTAINER_GYMCLASS_SERVICE_URL=${CONTAINER_GYMCLASS_SERVICE_URL}
      - GYMCLASS_SERVICE_URL=${GYMCLASS_SERVICE_URL}
    networks:
        redinterna:
          aliases:
            - "ms-user.powerapp.localhost"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ms-user.rule=Host(`ms-user.powerapp.localhost`)"
      - "traefik.http.routers.ms-user.tls=true"
      - "traefik.http.services.ms-user.loadbalancer.server.port=5000"
      - "traefik.docker.network=redinterna"
      - "traefik.http.middlewares.ms-user.circuitbreaker.expression=LatencyAtQuantileMS(50.0) > 100"
      - "traefik.http.middlewares.ms-user.circuitbreaker.expression=ResponseCodeRatio(500, 600, 0, 600) > 0.25"
      - "traefik.http.middlewares.ms-user.circuitbreaker.expression=NetworkErrorRatio() > 0.5"

  ms-gym_class:
    image: ms-gym_class:v1.0.0
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_URL=${DB_URL_GYMCLASS}
      - POSTGRES_DB=${DB_NAME_GYMCLASS}
      - CONTAINER_USER_SERVICE_URL=${CONTAINER_USER_SERVICE_URL}
      - USER_SERVICE_URL=${USER_SERVICE_URL}
      - CONTAINER_INSTRUCTOR_SERVICE_URL=${CONTAINER_INSTRUCTOR_SERVICE_URL}
      - INSTRUCTOR_SERVICE_URL=${INSTRUCTOR_SERVICE_URL}
      - CONTAINER_GYMCLASS_SERVICE_URL=${CONTAINER_GYMCLASS_SERVICE_URL}
      - GYMCLASS_SERVICE_URL=${GYMCLASS_SERVICE_URL}
    networks:
        redinterna:
          aliases:
            - "ms-gymclass.powerapp.localhost"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ms-gymclass.rule=Host(`ms-gymclass.powerapp.localhost`)"
      - "traefik.http.routers.ms-gymclass.tls=true"
      - "traefik.http.services.ms-gymclass.loadbalancer.server.port=5000"
      - "traefik.docker.network=redinterna"
      - "traefik.http.middlewares.ms-gymclass.circuitbreaker.expression=LatencyAtQuantileMS(50.0) > 100"
      - "traefik.http.middlewares.ms-gymclass.circuitbreaker.expression=ResponseCodeRatio(500, 600, 0, 600) > 0.25"
      - "traefik.http.middlewares.ms-gymclass.circuitbreaker.expression=NetworkErrorRatio() > 0.5"

  ms-instructor:
    image: ms-instructor:v1.0.0
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_URL=${DB_URL_INSTRUCTOR}
      - POSTGRES_DB=${DB_NAME_INSTRUCTOR}
      - CONTAINER_USER_SERVICE_URL=${CONTAINER_USER_SERVICE_URL}
      - USER_SERVICE_URL=${USER_SERVICE_URL}
      - CONTAINER_INSTRUCTOR_SERVICE_URL=${CONTAINER_INSTRUCTOR_SERVICE_URL}
      - INSTRUCTOR_SERVICE_URL=${INSTRUCTOR_SERVICE_URL}
      - CONTAINER_GYMCLASS_SERVICE_URL=${CONTAINER_GYMCLASS_SERVICE_URL}
      - GYMCLASS_SERVICE_URL=${GYMCLASS_SERVICE_URL}
    networks:
        redinterna:
          aliases:
            - "ms-instructor.powerapp.localhost"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ms-instructor.rule=Host(`ms-instructor.powerapp.localhost`)"
      - "traefik.http.routers.ms-instructor.tls=true"
      - "traefik.http.services.ms-instructor.loadbalancer.server.port=5000"
      - "traefik.docker.network=redinterna"
      - "traefik.http.middlewares.ms-instructor.circuitbreaker.expression=LatencyAtQuantileMS(50.0) > 100"
      - "traefik.http.middlewares.ms-instructor.circuitbreaker.expression=ResponseCodeRatio(500, 600, 0, 600) > 0.25"
      - "traefik.http.middlewares.ms-instructor.circuitbreaker.expression=NetworkErrorRatio() > 0.5"


networks:
  redinterna:
    external: true