http:
  routers:
    traefik:
      rule: "Host(`traefik.powerapp.localhost`)"
      service: "api@internal"
      tls:
        domains:
          - main: "powerapp.localhost"
            sans:
              - "*.powerapp.localhost"
          - main: "powerapp.local"
            sans:
              - "*.powerapp.local"

tls:
  certificates:
    - certFile: "/etc/certs/powerapp-cert.pem"
      keyFile: "/etc/certs/powerapp-key.pem"
