services:
  traefik:
    image: traefik:v2.0
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--providers.docker.exposedbydefault=false"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./config/config.yml:/etc/traefik/config.yml"
      - "./config/traefik.yml:/etc/traefik/traefik.yml"
      - "./certs:/etc/traefik/certs"
    networks:
      - redinterna

networks:
  redinterna:
    external: true